services:
  blog:
    container_name: wikimoe-blog-nuxt
    build:
      context: ./blog
      args:
        - TZ=Asia/Shanghai
        - NUXT_API_DOMAIN=${NUXT_API_DOMAIN}
        - SWR_ENABLED=${SWR_ENABLED}
        - SWR_CACHE_MAXAGE=${SWR_CACHE_MAXAGE}
        - SWR_CACHE_STALEMAXAGE=${SWR_CACHE_STALEMAXAGE}
        - CACHE_MAX_PAGE=${CACHE_MAX_PAGE}
        - CACHE_TTL=${CACHE_TTL}
    environment:
      - TZ=Asia/Shanghai
      - NUXT_API_DOMAIN=${NUXT_API_DOMAIN}
      - SWR_ENABLED=${SWR_ENABLED}
      - SWR_CACHE_MAXAGE=${SWR_CACHE_MAXAGE}
      - SWR_CACHE_STALEMAXAGE=${SWR_CACHE_STALEMAXAGE}
      - CACHE_MAX_PAGE=${CACHE_MAX_PAGE}
      - CACHE_TTL=${CACHE_TTL}
    ports:
      - '3007:3007'
    depends_on:
      - server
    networks:
      - wikimoe
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '378M'
        reservations:
          cpus: '0.25'
          memory: '128M'
  server:
    container_name: wikimoe-blog-server
    image: eeg1412/wikimoe-blog-server:latest
    environment:
      - TZ=Asia/Shanghai
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - JSON_LIMIT=${JSON_LIMIT}
      - URLENCODED_LIMIT=${URLENCODED_LIMIT}
      - JWT_SECRET=${JWT_SECRET}
      - IP2LOCATION=${IP2LOCATION}
      - IP2LOCATION_FILE_NAME=${IP2LOCATION_FILE_NAME}
      - MAX_HISTORYLOGS_SIZE=${MAX_HISTORYLOGS_SIZE}
      - USER_NAME=${USER_NAME} # option
    volumes:
      - ./data/wikimoe-blog-server/log:/app/log
      - ./data/wikimoe-blog-server/ip2location:/app/utils/ip2location
      - ./data/wikimoe-blog-server/backups:/app/backups
      - ./data/wikimoe-blog-server/cache:/app/cache
      - ./data/wikimoe-blog-server/public:/app/public
    ports:
      - '3006:3006'
    depends_on:
      - mongo
    networks:
      - wikimoe
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '378M'
        reservations:
          cpus: '0.25'
          memory: '128M'

  mongo:
    container_name: wikimoe-db
    image: mongo:6.0.12-jammy
    volumes:
      - ./data/db:/data/db
    networks:
      - wikimoe
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '512M'
        reservations:
          cpus: '0.25'
          memory: '256M'

networks:
  wikimoe:
    driver: bridge
